### ISSUE TITLE
Create OS X System Font

### ISSUE THREAD

**Issue by Tekl** [antijingoist/open-dyslexic#53]
Create a special font version to replace Yosemite's System Font. You just have to export it with the PostScript Name ".HelveticaNeueDeskInterface-Regular". For more details look here:
http://www.macissues.com/2014/11/21/how-to-change-the-default-system-font-in-mac-os-x/
https://github.com/dtinth/YosemiteSystemFontPatcher
##

**Comment by antijingoist** [comment]
It appears that YosemiteSystemFontPatcher doing this with OpenDyslexic out of the box.

**Comment by Tekl** [comment]
Yes, that's true, but not everyone is able to use the tool. And the Font needs some adjustments to fit well in the UI.

**Comment by antijingoist** [comment]
OpenDyslexic would need to become metric compatible with Helvetica Neue, and kept up to date with MacOS changes.
I'm not opposed to this happening, but I couldn't maintain it time-wise. If you want to send a pull request with this version, that'll be fantastic, and I'll pull it into the repo. Otherwise, I sincerely do not have the time to maintain it solo.

**Comment by Tekl** [comment]
I think it must not fully metric compatible to Helvetica. It seems some little adjustments would help. I don't know much about that. Maybe the friendly guys from Font Bureau can give you the right tips. They also adjusted their Input font for OS X. http://input.fontbureau.com/systemfont/

**Comment by antijingoist** [comment]
If added, it would likely be a different project.
